### ISSUE TITLE
Hererocks fails to install in Windows

### ISSUE THREAD

**Issue by ishchow** [wbthomason/packer.nvim#302]
I tried to install some luarocks in Windows and I got this error. I tried running nvim as both admin and non-admin, still hitting same error.

![image](https://user-images.githubusercontent.com/15524738/115152580-85449d80-a026-11eb-8f54-bfa304c5a864.png)

There wasn't a specific error message shown compared to when a plugin fails to install. `$HOME\AppData\Local\Temp\nvim\packer.nvim.log` doesn't contain any error messages for the hererocks installation process either.

These are the relevant lines from my [packer config](https://github.com/ishchow/dotfiles/blob/144586b58379d2aa5c099651a21d937469b5d456/dot_config/nvim/lua/plugins.lua#L74-L76)

```lua
    -- #### Lua Rocks ####
    use_rocks 'penlight' -- Useful lua modules
    -- #### Lua Rocks ####
```

I can confirm that I can install hererocks on it's own without packer:

```powershell
PS C:\WINDOWS\system32> python --version
Python 3.9.1

PS C:\WINDOWS\system32> pip3 --version
pip 20.2.3 from c:\python39\lib\site-packages\pip (python 3.9)

PS C:\WINDOWS\system32> pip3 install hererocks
Collecting hererocks
  Using cached hererocks-0.23.0-py3-none-any.whl (33 kB)
Installing collected packages: hererocks
Successfully installed hererocks-0.23.0
WARNING: You are using pip version 20.2.3; however, version 21.0.1 is available.
You should consider upgrading via the 'c:\python39\python.exe -m pip install --upgrade pip' command.
```

**Comment by ishchow** [comment]
So I just updated packer and tried it again. This is the latest from the log file:

```
[ERROR 4/19/2021 9:27:50 PM] ...site\pack\packer\opt\packer.nvim\lua\packer\luarocks.lua:69: Failed to install hererocks: {
  exit_code = 1,
  signal = 0
}
```

Would there be a way to capture the output of the command?

**Comment by IAmIlliest** [comment]
I'm seeing the same issue. Both when running nvim inside Windows Terminal or Neovim-qt as admin.

**Comment by wbthomason** [comment]
Sorry, I'm super behind on `packer` issues right now. The next steps here should be to figure out what an exit status of 1 means for `hererocks.py` in particular. Would you be willing to try manually running `hererocks` using `python hererocks.py --verbose -j 2.0.5 -r latest <INSTALL_DIR>` where `<INSTALL_DIR>` should be `stdpath('cache')\packer_hererocks\2.0.5`, and report the output?

**Comment by IAmIlliest** [comment]
No worries, give me a day or two in order to get python and friends setup, and then test it....software developer skills; I have not :-)

**Comment by IAmIlliest** [comment]
Sorry for the verbosity, just trying to give some extra context as you might notice confouding factors that I'm not aware of.

**### System Context**

> Terminal Environment:
> 	* Windows Terminal (admin)
> 	* Powershell Core 7.1.3
> Python Environment:
> 	* Using Conda
> 	* conda --version
> 		conda 4.10.1
> 	* Conda Environment: 'env_testing'

**### Steps**

1. Install hererocks:
```
	python -m pip install hererocks
	Collecting hererocks
	  Downloading hererocks-0.23.0-py3-none-any.whl (33 kB)
	Successfully installed hererocks-0.23.0
```

2. Determine path in nvim:
```
	echo stdpath('cache')
	E:\111_Portable\XDG\cache\nvim
```

3. Run command (outside of NeoVim, not sure if that was what you need?):
```
(env_testing) PS C:\Users\Kris.DESKTOP-L5S24O2> python "C:\Users\Kris.DESKTOP-L5S24O2\.conda\envs\env_testing\Lib\site-packages\hererocks.py" --verbose -j 2.0.5 -r latest E:\111_Portable\XDG\cache\nvim\packer_hererocks\2.0.5
	Querying registry key HKEY_LOCAL_MACHINE\Software\Microsoft\VisualStudio\14.0\Setup\VC:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Wow6432Node\Microsoft\VisualStudio\14.0\Setup\VC:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Microsoft\VCExpress\14.0\Setup\VS:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Wow6432Node\Microsoft\VCExpress\14.0\Setup\VS:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Microsoft\VisualStudio\12.0\Setup\VC:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Wow6432Node\Microsoft\VisualStudio\12.0\Setup\VC:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Microsoft\VCExpress\12.0\Setup\VS:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Wow6432Node\Microsoft\VCExpress\12.0\Setup\VS:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Microsoft\VisualStudio\11.0\Setup\VC:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Wow6432Node\Microsoft\VisualStudio\11.0\Setup\VC:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Microsoft\VCExpress\11.0\Setup\VS:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Wow6432Node\Microsoft\VCExpress\11.0\Setup\VS:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Microsoft\VisualStudio\10.0\Setup\VC:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Wow6432Node\Microsoft\VisualStudio\10.0\Setup\VC:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Microsoft\VCExpress\10.0\Setup\VS:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Wow6432Node\Microsoft\VCExpress\10.0\Setup\VS:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Microsoft\Microsoft SDKs\Windows\v7.1:InstallationFolder
	Querying registry key HKEY_LOCAL_MACHINE\Software\Wow6432Node\Microsoft\Microsoft SDKs\Windows\v7.1:InstallationFolder
	Querying registry key HKEY_LOCAL_MACHINE\Software\Microsoft\VisualStudio\9.0\Setup\VC:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Wow6432Node\Microsoft\VisualStudio\9.0\Setup\VC:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Microsoft\VCExpress\9.0\Setup\VS:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Wow6432Node\Microsoft\VCExpress\9.0\Setup\VS:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Microsoft\Microsoft SDKs\Windows\v6.1:InstallationFolder
	Querying registry key HKEY_LOCAL_MACHINE\Software\Wow6432Node\Microsoft\Microsoft SDKs\Windows\v6.1:InstallationFolder
	Querying registry key HKEY_LOCAL_MACHINE\Software\Microsoft\VisualStudio\14.0\Setup\VC:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Wow6432Node\Microsoft\VisualStudio\14.0\Setup\VC:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Microsoft\VCExpress\14.0\Setup\VS:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Wow6432Node\Microsoft\VCExpress\14.0\Setup\VS:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Microsoft\VisualStudio\12.0\Setup\VC:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Wow6432Node\Microsoft\VisualStudio\12.0\Setup\VC:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Microsoft\VCExpress\12.0\Setup\VS:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Wow6432Node\Microsoft\VCExpress\12.0\Setup\VS:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Microsoft\VisualStudio\11.0\Setup\VC:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Wow6432Node\Microsoft\VisualStudio\11.0\Setup\VC:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Microsoft\VCExpress\11.0\Setup\VS:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Wow6432Node\Microsoft\VCExpress\11.0\Setup\VS:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Microsoft\VisualStudio\10.0\Setup\VC:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Wow6432Node\Microsoft\VisualStudio\10.0\Setup\VC:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Microsoft\VCExpress\10.0\Setup\VS:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Wow6432Node\Microsoft\VCExpress\10.0\Setup\VS:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Microsoft\Microsoft SDKs\Windows\v7.1:InstallationFolder
	Querying registry key HKEY_LOCAL_MACHINE\Software\Wow6432Node\Microsoft\Microsoft SDKs\Windows\v7.1:InstallationFolder
	Querying registry key HKEY_LOCAL_MACHINE\Software\Microsoft\VisualStudio\9.0\Setup\VC:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Wow6432Node\Microsoft\VisualStudio\9.0\Setup\VC:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Microsoft\VCExpress\9.0\Setup\VS:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Wow6432Node\Microsoft\VCExpress\9.0\Setup\VS:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Microsoft\Microsoft SDKs\Windows\v6.1:InstallationFolder
	Querying registry key HKEY_LOCAL_MACHINE\Software\Wow6432Node\Microsoft\Microsoft SDKs\Windows\v6.1:InstallationFolder
	Error: couldn't set up MSVC toolchain
	(env_testing)
```

4. Run command (outside of NeoVim, again) using hererocks.py file that was already in "E:\111_Portable\XDG\cache\nvim\packer_hererocks\hererocks.py" (presumably from having already tried 'PackerRocks' commands and/or having "use_rocks {'luafilesystem'}" in my plugins...):
```
(env_testing) PS C:\Users\Kris.DESKTOP-L5S24O2> python "E:\111_Portable\XDG\cache\nvim\packer_hererocks\hererocks.py" --verbose -j 2.0.5 -r latest E:\111_Portable\XDG\cache\nvim\packer_hererocks\2.0.5
	Querying registry key HKEY_LOCAL_MACHINE\Software\Microsoft\VisualStudio\14.0\Setup\VC:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Wow6432Node\Microsoft\VisualStudio\14.0\Setup\VC:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Microsoft\VCExpress\14.0\Setup\VS:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Wow6432Node\Microsoft\VCExpress\14.0\Setup\VS:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Microsoft\VisualStudio\12.0\Setup\VC:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Wow6432Node\Microsoft\VisualStudio\12.0\Setup\VC:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Microsoft\VCExpress\12.0\Setup\VS:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Wow6432Node\Microsoft\VCExpress\12.0\Setup\VS:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Microsoft\VisualStudio\11.0\Setup\VC:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Wow6432Node\Microsoft\VisualStudio\11.0\Setup\VC:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Microsoft\VCExpress\11.0\Setup\VS:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Wow6432Node\Microsoft\VCExpress\11.0\Setup\VS:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Microsoft\VisualStudio\10.0\Setup\VC:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Wow6432Node\Microsoft\VisualStudio\10.0\Setup\VC:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Microsoft\VCExpress\10.0\Setup\VS:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Wow6432Node\Microsoft\VCExpress\10.0\Setup\VS:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Microsoft\Microsoft SDKs\Windows\v7.1:InstallationFolder
	Querying registry key HKEY_LOCAL_MACHINE\Software\Wow6432Node\Microsoft\Microsoft SDKs\Windows\v7.1:InstallationFolder
	Querying registry key HKEY_LOCAL_MACHINE\Software\Microsoft\VisualStudio\9.0\Setup\VC:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Wow6432Node\Microsoft\VisualStudio\9.0\Setup\VC:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Microsoft\VCExpress\9.0\Setup\VS:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Wow6432Node\Microsoft\VCExpress\9.0\Setup\VS:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Microsoft\Microsoft SDKs\Windows\v6.1:InstallationFolder
	Querying registry key HKEY_LOCAL_MACHINE\Software\Wow6432Node\Microsoft\Microsoft SDKs\Windows\v6.1:InstallationFolder
	Querying registry key HKEY_LOCAL_MACHINE\Software\Microsoft\VisualStudio\14.0\Setup\VC:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Wow6432Node\Microsoft\VisualStudio\14.0\Setup\VC:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Microsoft\VCExpress\14.0\Setup\VS:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Wow6432Node\Microsoft\VCExpress\14.0\Setup\VS:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Microsoft\VisualStudio\12.0\Setup\VC:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Wow6432Node\Microsoft\VisualStudio\12.0\Setup\VC:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Microsoft\VCExpress\12.0\Setup\VS:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Wow6432Node\Microsoft\VCExpress\12.0\Setup\VS:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Microsoft\VisualStudio\11.0\Setup\VC:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Wow6432Node\Microsoft\VisualStudio\11.0\Setup\VC:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Microsoft\VCExpress\11.0\Setup\VS:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Wow6432Node\Microsoft\VCExpress\11.0\Setup\VS:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Microsoft\VisualStudio\10.0\Setup\VC:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Wow6432Node\Microsoft\VisualStudio\10.0\Setup\VC:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Microsoft\VCExpress\10.0\Setup\VS:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Wow6432Node\Microsoft\VCExpress\10.0\Setup\VS:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Microsoft\Microsoft SDKs\Windows\v7.1:InstallationFolder
	Querying registry key HKEY_LOCAL_MACHINE\Software\Wow6432Node\Microsoft\Microsoft SDKs\Windows\v7.1:InstallationFolder
	Querying registry key HKEY_LOCAL_MACHINE\Software\Microsoft\VisualStudio\9.0\Setup\VC:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Wow6432Node\Microsoft\VisualStudio\9.0\Setup\VC:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Microsoft\VCExpress\9.0\Setup\VS:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Wow6432Node\Microsoft\VCExpress\9.0\Setup\VS:ProductDir
	Querying registry key HKEY_LOCAL_MACHINE\Software\Microsoft\Microsoft SDKs\Windows\v6.1:InstallationFolder
	Querying registry key HKEY_LOCAL_MACHINE\Software\Wow6432Node\Microsoft\Microsoft SDKs\Windows\v6.1:InstallationFolder
	Error: couldn't set up MSVC toolchain
	(env_testing)
```

**Comment by IAmIlliest** [comment]
So, I have no idea what I'm doing, but do know how to open things in vim....so....I'm guessing the issue is to do with use of the MSCV toolchain on Windows, rather than GNU's tools. Line 1730-1753 of hererocls.py:

`
@staticmethod
    def add_cflags_to_msvcbuild(cflags):
        with open("msvcbuild.bat", "rb") as msvcbuild_file:
            msvcbuild_src = msvcbuild_file.read()

        start, assignment, value_and_rest = msvcbuild_src.partition(b"@set LJCOMPILE")
        value_and_rest = value_and_rest.decode("UTF-8")

        with open("msvcbuild.bat", "wb") as msvcbuild_file:
            msvcbuild_file.write(start)
            msvcbuild_file.write(assignment)
            msvcbuild_file.write(value_and_rest.replace("\r\n", " {}\r\n".format(cflags), 1).encode("UTF-8"))

    def make(self):
        cflags = list(self.compat_cflags)

        if opts.cflags is not None:
            cflags.extend(opts.cflags.split())

        if using_cl():
            with self.in_source_files_prefix():
                if cflags:
                    self.add_cflags_to_msvcbuild(" ".join(cflags))

                run("msvcbuild.bat")
`

**Comment by IAmIlliest** [comment]
Is this an old version of hererocks / lua by any chance?
I'm just getting the impression that it's using an old version that is lacking Windows support....but I also don't really know what I'm talking about, it just seems to be a referencing a lot of very Linux only looking stuff in the source....

I got past the MSVC errors by installing the 2015 MSVC tools.

It's now stumbling looking for what seems to be a very old version of a lua library (lua51.dll). I have downloaded lua 5.1.5 (newest Windows binary version I could find with lua51.dll - ), and extracted it to the first dir in my $PATH, but I'm still getting the not found error, and I don't really know how to debug the source of this traceback:

```
python "E:\111_Portable\XDG\cache\nvim\packer_hererocks\hererocks.py" --verbose -j 2.0.5 -r latest E:\111_Portable\XDG\cache\nvim\packer_hererocks\2.0.5
Querying registry key HKEY_LOCAL_MACHINE\Software\Microsoft\VisualStudio\14.0\Setup\VC:ProductDir
Querying registry key HKEY_LOCAL_MACHINE\Software\Wow6432Node\Microsoft\VisualStudio\14.0\Setup\VC:ProductDir
Checking existence of C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\vcvars64.bat
Setting up VS 14.0 (x64)
Running call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\vcvars64.bat"
Running cl
Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24245 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

usage: cl [ option... ] filename... [ /link linkoption... ]
Fetching LuaJIT 2.0.5 (target: vs) (cached)
Verifying SHA256 checksum
Building LuaJIT 2.0.5 (target: vs)
Running msvcbuild.bat

C:\Users\CHRIS~1.DES\AppData\Local\Temp\tmpnkbaz3cq\LuaJIT-2.0.5\src>cl /nologo /c /O2 /W3 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_STDIO_INLINE=__declspec(dllexport)__inline host\minilua.c
minilua.c

C:\Users\CHRIS~1.DES\AppData\Local\Temp\tmpnkbaz3cq\LuaJIT-2.0.5\src>link /nologo /out:minilua.exe minilua.obj
LINK : fatal error LNK1104: cannot open file 'kernel32.lib'

*******************************************************
*** Build FAILED -- Please check the error messages ***
*******************************************************
Installing LuaJIT 2.0.5 (target: vs)
Traceback (most recent call last):
  File "E:\111_Portable\XDG\cache\nvim\packer_hererocks\hererocks.py", line 2510, in <module>
    main()
  File "E:\111_Portable\XDG\cache\nvim\packer_hererocks\hererocks.py", line 2484, in main
    opts = parser.parse_args(argv)
  File "C:\ProgramData\Miniconda3\envs\env_system\lib\argparse.py", line 1755, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "C:\ProgramData\Miniconda3\envs\env_system\lib\argparse.py", line 1787, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "C:\ProgramData\Miniconda3\envs\env_system\lib\argparse.py", line 1993, in _parse_known_args
    start_index = consume_optional(start_index)
  File "C:\ProgramData\Miniconda3\envs\env_system\lib\argparse.py", line 1933, in consume_optional
    take_action(action, args, option_string)
  File "C:\ProgramData\Miniconda3\envs\env_system\lib\argparse.py", line 1861, in take_action
    action(self, namespace, argument_values, option_string)
  File "E:\111_Portable\XDG\cache\nvim\packer_hererocks\hererocks.py", line 2289, in __call__
    main(args_content.split("\r\n")[1:])
  File "E:\111_Portable\XDG\cache\nvim\packer_hererocks\hererocks.py", line 2502, in main
    install_programs(argv is not None)
  File "E:\111_Portable\XDG\cache\nvim\packer_hererocks\hererocks.py", line 2327, in install_programs
    if LuaJIT(opts.luajit).update_identifiers(identifiers):
  File "E:\111_Portable\XDG\cache\nvim\packer_hererocks\hererocks.py", line 609, in update_identifiers
    self.install()
  File "E:\111_Portable\XDG\cache\nvim\packer_hererocks\hererocks.py", line 781, in install
    self.make_install()
  File "E:\111_Portable\XDG\cache\nvim\packer_hererocks\hererocks.py", line 1780, in make_install
    copy_files(os.path.join(opts.location, "bin"), dll_file)
  File "E:\111_Portable\XDG\cache\nvim\packer_hererocks\hererocks.py", line 428, in copy_files
    shutil.copy(src, path)
  File "C:\ProgramData\Miniconda3\envs\env_system\lib\shutil.py", line 248, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\ProgramData\Miniconda3\envs\env_system\lib\shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'lua51.dll'
```

Offending code block:

```
def copyfile(src, dst, *, follow_symlinks=True):
    """Copy data from src to dst.

    If follow_symlinks is not set and src is a symbolic link, a new
    symlink will be created instead of copying the file it points to.

    """
    if _samefile(src, dst):
        raise SameFileError("{!r} and {!r} are the same file".format(src, dst))

    for fn in [src, dst]:
        try:
            st = os.stat(fn)
        except OSError:
            # File most likely does not exist
            pass
        else:
            # XXX What about other special files? (sockets, devices...)
            if stat.S_ISFIFO(st.st_mode):
                raise SpecialFileError("`%s` is a named pipe" % fn)

    if not follow_symlinks and os.path.islink(src):
        os.symlink(os.readlink(src), dst)
    else:
        with open(src, 'rb') as fsrc:
            with open(dst, 'wb') as fdst:
                copyfileobj(fsrc, fdst)
    return dst
```

**Comment by IAmIlliest** [comment]
Hmmm, just noticed the 5.1.5 binary for the interpreter that I downloaded is **lua5.1.dll** not **lua51.dll**

Not sure if that's a typo somewhere in the source, or if I have the wrong binary version....

**Comment by wbthomason** [comment]
Thanks, this is super helpful! The version of `hererocks` shouldn't be outdated - `packer`, at least, downloads the latest release from Github. You're seeing Lua 5.1 because that's the Lua version that Neovim and LuaJIT support (later versions of Lua make breaking changes, and LuaJIT was never rebuilt for those versions).

Given everything you have here, I'm now curious if anyone has actually gotten `hererocks` working on Windows at all via `packer`. It seems as though `hererocks` just doesn't work for Windows?

**Comment by wbthomason** [comment]
Have you tried installing the `gcc` tools via MinGW?

**Comment by IAmIlliest** [comment]
No I haven't as yet, I've been giving myself a crash course in Visual Studio Code to try and work out how to properly debug the traceback. Not much luck as yet, just hitting walls of errors and exceptions, and get the breakpoints working properly.

I'll try the gcc compiler and see what happens from there, and then perhaps have a bash at a different debugger if I get the same result.

**Comment by arcashka** [comment]
> Given everything you have here, I'm now curious if anyone has actually gotten hererocks working on Windows at all via packer. It seems as though hererocks just doesn't work for Windows?

I have the same problem on Windows as in the description

Windows
NVIM v0.6.1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

**Comment by arcashka** [comment]
I found more recent version of this issue https://github.com/wbthomason/packer.nvim/issues/805
